FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    qemu-system-x86 \
    qemu-utils \
    wget \
    gzip \
    python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

COPY docker/run_iotgoat.py /opt/run_iotgoat.py

EXPOSE 2222 8080 4443

CMD ["python3", "/opt/run_iotgoat.py"]
