FROM python:3.9-slim

RUN apt-get update && apt-get install -y iptables && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY plc.py requirements.txt ./
RUN pip install -r requirements.txt

CMD ["python", "plc.py"]
