config setup
    charondebug="all"
    uniqueids=yes

conn scada-vpn
    auto=add
    keyexchange=ikev2
    type=tunnel
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    dpdaction=clear
    dpddelay=30s
    dpdtimeout=120s
    fragmentation=yes

    left=%any
    leftid=@scada-vpn
    leftsubnet=172.20.0.0/24
    leftcert=server-cert.pem
    leftauth=pubkey

    right=%any
    rightid=%any
    rightauth=pubkey
    rightsourceip=10.10.0.0/24
    rightsubnet=0.0.0.0/0
